"""Writing a complete KiCad project for the fixture.

Only new projects are ever written. Nothing here opens an existing KiCad file and rewrites it --
that is what breaks the UUID cross-references KiCad keeps between a symbol, its instance data and
the footprint on the board. Regenerating is safe because the identifiers are derived from the
config rather than randomised, so an unchanged config produces a byte-identical project.
"""

from __future__ import annotations

import json
from dataclasses import dataclass
from datetime import datetime, timezone
from pathlib import Path

from .. import __version__
from ..board import Board
from ..checks import ERROR, Finding, Limits
from ..checks import run as check_board
from ..config import FixtureConfig, validate
from . import pcb as pcb_builder
from . import schematic as sch_builder
from .footprint import mounting_hole_name, mounting_hole_shape, pogo_shape
from .library import LibraryError
from .pcb import GROUND_POUR_INSET_MM


class ProjectError(Exception):
    """The config did not validate, or KiCad's libraries are missing, so nothing was written."""

    def __init__(self, findings: list[Finding]):
        self.findings = findings
        blocking = [f for f in findings if f.severity == ERROR]
        super().__init__(f"{len(blocking)} error(s); no project was written")


@dataclass
class Result:
    out_dir: Path
    files: list[Path]
    findings: list[Finding]
    probes_placed: int
    unplaced: list[str]


def _project_json(config: FixtureConfig) -> str:
    """A .kicad_pro with the design rules a fixture actually needs.

    The clearances are loose on purpose. A fixture is a one-off carrying no fast edges, and the
    cheapest fabrication class is plenty -- there is no reason to pay for 0.1 mm tracks here.
    """
    probe = config.probe_part
    data = {
        "board": {
            "design_settings": {
                "rules": {
                    "min_clearance": 0.2,
                    "min_through_hole_diameter": 0.3,
                    "min_track_width": 0.25,
                    "min_via_diameter": 0.6,
                    "min_hole_to_hole": 0.25,
                    "min_copper_edge_clearance": 0.5,
                },
                "defaults": {
                    "board_outline_line_width": 0.1,
                    "silk_line_width": 0.12,
                    "silk_text_size_h": 1.0,
                    "silk_text_size_v": 1.0,
                },
            },
        },
        "meta": {"filename": f"{config.name}.kicad_pro", "version": 3},
        "net_settings": {
            "classes": [
                {
                    "name": "Default",
                    "clearance": 0.2,
                    "track_width": 0.3,
                    "via_diameter": 0.8,
                    "via_drill": 0.4,
                }
            ],
        },
        "pcbnew": {"page_layout_descr_file": ""},
        "schematic": {"legacy_lib_dir": "", "legacy_lib_list": []},
        "sheets": [[sch_builder.Sheet(config).root_uuid, "Root"]],
        "text_variables": {
            "FIXTURE": config.name,
            "DUT": config.dut_board or "unspecified",
            "PROBE": probe.receptacle,
            "PINSIDE": __version__,
        },
    }
    return json.dumps(data, indent=2) + "\n"


def _fp_lib_table() -> str:
    """Point the project at its own footprint library, so the pogo footprint resolves."""
    return (
        "(fp_lib_table\n"
        "\t(version 7)\n"
        "\t(lib\n"
        '\t\t(name "pinside")\n'
        '\t\t(type "KiCad")\n'
        '\t\t(uri "${KIPRJMOD}/pinside.pretty")\n'
        '\t\t(options "")\n'
        '\t\t(descr "Pogo probes generated by pinside")\n'
        "\t)\n"
        ")\n"
    )


def _hardware_note(probes: int, probe, holes: int) -> str:
    """What the plate force means for the hardware that has to carry it.

    The number itself was already in the generated README and nobody could act on it. Newtons
    are not what anyone buys; what they need to know is whether a hand clamp will do, how many
    standoffs are carrying the load, and how much each one takes.
    """
    newtons = probes * probe.force_n
    kgf = newtons / 9.81
    per_hole = newtons / holes if holes else 0.0

    if kgf < 2:
        verdict = (
            "A hand clamp or a couple of thumbscrews will close this. The load is small enough "
            "that the plate's own stiffness is what decides whether contact is even."
        )
    elif kgf < 10:
        verdict = (
            "This is past comfortable finger pressure. Use a toggle clamp or screws; a plate "
            "held down by hand will make intermittent contact on whichever probe is furthest "
            "from where you are pressing."
        )
    else:
        verdict = (
            "This needs a lever or pneumatic clamp, and the plate needs to be stiff enough not "
            "to bow between its supports. At this load a 1.6 mm FR4 plate deflects visibly and "
            "the probes in the middle stop reaching."
        )

    lines = [
        f"{probes} probes at {probe.force_n} N each is **{newtons:.0f} N** "
        f"({kgf:.1f} kgf) at full travel.",
        "",
        verdict,
        "",
    ]
    if holes:
        lines += [
            f"That load is carried by the DUT's {holes} mounting holes, so roughly "
            f"**{per_hole:.0f} N ({per_hole / 9.81:.1f} kgf) per standoff**. Use a standoff "
            f"rated well above that: they are specified for axial load, and the number that "
            f"matters here is the compressive one, not the thread's tensile rating.",
            "",
            f"Allow at least {probe.travel_mm} mm of probe travel plus the DUT's thickness in "
            "the standoff length, or the plate bottoms out before the pins compress.",
        ]
    else:
        lines += [
            "The DUT has no mounting holes, so there is nowhere to put a standoff. The plate "
            "has to be located some other way, and whatever locates it carries all of this.",
        ]
    return "\n".join(lines)


def _readme(
    config: FixtureConfig, board: Board | None, result_probes: int, unplaced: list[str]
) -> str:
    module = config.module
    probe = config.probe_part
    box = board.outline.bbox if board else None
    frame = (board.frame or {}) if board else {}

    controller = (
        f"**{module.description}**\n\nIts footprint is placed off the board edge; move "
        f"it where you want it.\n"
        if module
        else f"**Bare {config.mcu} on the fixture board.** The schematic does not draw it: "
        f"add the MCU, its supply, crystal and USB, then wire the `FIX_*` nets.\n"
    )

    provenance = (
        "These dimensions were transcribed from a catalogue and nobody has checked them against "
        "the supplier's own drawing. **Do that before you order**: series get revised, and a "
        "receptacle 0.1 mm fatter than this expects is a board that has to be redrilled."
        if not probe.verified
        else f"Checked against the supplier drawing: {probe.verified}."
    )
    inset = GROUND_POUR_INSET_MM
    hole_count = len(board.mounting_holes) if board else 0
    hardware = _hardware_note(result_probes, probe, hole_count)

    unplaced_note = ""
    if unplaced:
        unplaced_note = (
            "\n## Probes that were not placed\n\n"
            "These channels name a DUT signal with no test point on the board, so there was "
            "nowhere to put them:\n\n" + "\n".join(f"- `{name}`" for name in unplaced) + "\n"
        )

    return f"""# {config.name} fixture board

Generated by pinside {__version__} on {datetime.now(timezone.utc).strftime("%Y-%m-%d")} from
`{Path(config.source).name if config.source else "the fixture config"}`.

**Regenerating overwrites this project.** Change the config, not the board, except for routing,
which pinside does not generate and will not overwrite once you have done it. If you intend to
route it, copy the project somewhere else first.

## What is already right

The part that has to be exact is the placement, and it is not laid out here at all: it is read
out of the DUT and carried through the fixture transform:

- **{result_probes} probes**, each at its DUT test point's own coordinates.
- **The outline and mounting holes**, taken from the DUT, so the two boards bolt together.
- Frame: origin `{frame.get("origin", "?")}`, mirror `{frame.get("mirror", "none")}`.
{f"- Board: {box.width:g} x {box.height:g} mm." if box else ""}

## What is left to you

- **Routing.** A ratsnest and an accurate drill plan are the useful part; guessing trace paths is
  not. Autoroute it or draw it.
- **Placing the controller and any connectors.**
- **Filling the zones.** A GND pour is already drawn on both copper layers, held
  {inset:g} mm back from the edge. KiCad fills it on `Edit > Fill All Zones`.

## The probe

{probe.description}

| | |
|---|---|
| Receptacle | `{probe.receptacle}` |
| Spring pin | `{probe.pin}` |
| Hole | {probe.drill_mm} mm |
| Pad | {probe.pad_mm} mm |
| Minimum pitch | {probe.min_pitch_mm} mm |
| Travel | {probe.travel_mm} mm |
| Force | {probe.force_n} N per pin at mid-travel |
| Mounting | {probe.mounting} |
| Source | {probe.source or "not recorded"} |
| Checked against the drawing | {probe.verified or "**no**"} |

{provenance}

The footprint is generated into `pinside.pretty/`, and `fp-lib-table` already points at it.

## Closing force

{hardware}

## The controller

{controller}
## Mirroring

`mirror = {frame.get("mirror", "none")}`. A fixture whose probes point up takes the DUT face-down,
which mirrors X. Get this wrong and the board is a perfect mirror image of the one you need, so
before ordering, print `pinside check <dut> -f svg` at 1:1 and lay the real board on it.
{unplaced_note}"""


def generate_project(
    config: FixtureConfig, board: Board | None, out_dir: str | Path, force: bool = False
) -> Result:
    findings = validate(config, board)

    # The board's own geometry is checked here too, and for a fixture it is the check that
    # matters most: a DUT whose test points are still at their netlist-import coordinates yields
    # a fixture with every hole in the wrong place, and nothing about the output looks wrong
    # until it comes back from the fab. The probe sets the spacing limit, so choosing a finer
    # pin relaxes it without a second edit.
    if board is not None:
        # The probe the config chose is what the board is being checked against, so its own
        # dimensions set the limits rather than the defaults.
        probe = config.probe_part
        findings = findings + check_board(
            board,
            Limits(probe_pitch=probe.min_pitch_mm, probe_body=probe.body_dia_mm),
        )

    if any(f.severity == ERROR for f in findings):
        raise ProjectError(findings)

    if board is None:
        raise ProjectError(
            [
                Finding(
                    "PK001",
                    ERROR,
                    "a fixture board cannot be laid out without the DUT board",
                    [config.dut_board or "(none)"],
                    "point dut.board at the .kicad_pcb, or pass --board",
                )
            ]
        )

    out = Path(out_dir)
    # Writing into someone else's directory is the one mistake that cannot be undone from here.
    already_ours = (out / f"{config.name}.kicad_pro").exists()
    if out.exists() and any(out.iterdir()) and not force and not already_ours:
        raise ProjectError(
            [
                Finding(
                    "PK002",
                    ERROR,
                    f"{out} is not empty and was not generated by pinside",
                    [str(out)],
                    "pass --force to write into it anyway",
                )
            ]
        )

    module = config.module
    probe = config.probe_part

    try:
        schematic_text = sch_builder.build(config, module, probe)
    except LibraryError as err:
        raise ProjectError([Finding("PK003", ERROR, str(err), [])]) from None

    # Which probes actually found a home, so the README can be honest about the rest.
    available = {t.signal for t in board.test_points if t.signal}
    wanted = pcb_builder._probe_map(config)
    unplaced = sorted(name for name, signal in wanted.items() if signal not in available)
    placed = len(wanted) - len(unplaced)

    board_text = pcb_builder.build(config, board, probe)

    written: list[Path] = []

    def write(relative: str, text: str) -> None:
        path = out / relative
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(text, encoding="utf-8")
        written.append(path)

    write(f"{config.name}.kicad_pro", _project_json(config))
    write(f"{config.name}.kicad_sch", schematic_text)
    write(f"{config.name}.kicad_pcb", board_text)
    write(
        f"pinside.pretty/{probe.footprint_name}.kicad_mod", pogo_shape(probe, config.name).library()
    )
    for drill, pad_dia in sorted(
        {(h.drill or 3.2, h.pad_diameter or 6.0) for h in board.mounting_holes}
    ):
        write(
            f"pinside.pretty/{mounting_hole_name(drill)}.kicad_mod",
            mounting_hole_shape(drill, pad_dia, config.name).library(),
        )
    write("fp-lib-table", _fp_lib_table())
    write("README.md", _readme(config, board, placed, unplaced))

    return Result(
        out_dir=out, files=written, findings=findings, probes_placed=placed, unplaced=unplaced
    )
