/* Everything the protocol core needs from hardware, and nothing more.
 *
 * The core is deliberately free of SDK headers so it can be built and tested on a host against
 * the mock in test/mock_hal.c. Anything platform-specific lives behind this interface.
 *
 * Generated by pinside. Regenerating overwrites this file.
 */
#ifndef FIXTURE_HAL_H
#define FIXTURE_HAL_H

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Pin directions, matching fx_gpio_desc.direction. */
enum { FX_DIR_INPUT = 0, FX_DIR_OUTPUT = 1, FX_DIR_OPEN_DRAIN = 2 };
enum { FX_PULL_NONE = 0, FX_PULL_UP = 1, FX_PULL_DOWN = 2 };
enum { FX_PARITY_NONE = 0, FX_PARITY_EVEN = 1, FX_PARITY_ODD = 2 };

/* Host link. Every byte the agent sees leaves through here. */
void fx_hal_write(const char *data, size_t len);

uint64_t fx_hal_millis(void);

void fx_hal_gpio_configure(uint8_t pin, int direction, int pull);
bool fx_hal_gpio_get(uint8_t pin);
void fx_hal_gpio_set(uint8_t pin, bool level);
/* Let the pin float: an open-drain output released, or an output turned back into an input. */
void fx_hal_gpio_release(uint8_t pin);

/* Raw converter counts, full scale fx_hal_adc_full_scale() at fx_hal_adc_reference_mv(). */
uint16_t fx_hal_adc_read(uint8_t adc_channel);
uint16_t fx_hal_adc_full_scale(void);
uint16_t fx_hal_adc_reference_mv(void);

void fx_hal_uart_configure(uint8_t index, uint32_t baud, uint8_t data_bits,
                           uint8_t stop_bits, int parity);
size_t fx_hal_uart_write(uint8_t index, const uint8_t *data, size_t len);
size_t fx_hal_uart_read(uint8_t index, uint8_t *data, size_t max);

/* 0 on success, negative on NAK or bus error. */
int fx_hal_i2c_write(uint8_t index, uint8_t address, const uint8_t *data, size_t len,
                     bool hold_bus);
int fx_hal_i2c_read(uint8_t index, uint8_t address, uint8_t *data, size_t len);

void fx_hal_spi_configure(uint8_t index, uint32_t hz, uint8_t mode);
void fx_hal_spi_transfer(uint8_t index, const uint8_t *tx, uint8_t *rx, size_t len);

#ifdef __cplusplus
}
#endif
#endif /* FIXTURE_HAL_H */
