/* The JSON-RPC 2.0 protocol layer: newline-delimited requests in, responses and notifications out.
 *
 * Generated by pinside. Regenerating overwrites this file.
 */
#ifndef FIXTURE_CORE_H
#define FIXTURE_CORE_H

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Longest request the fixture will accept. A request is one line of JSON. */
#ifndef FX_LINE_MAX
#define FX_LINE_MAX 1024
#endif

/* Largest single payload, in bytes, carried as hex in either direction. */
#ifndef FX_PAYLOAD_MAX
#define FX_PAYLOAD_MAX 256
#endif

/* Responses are written straight to the host in chunks of this size rather than assembled in
 * one buffer, so a channel roster is not bounded by how much RAM the fixture can spare. */
#ifndef FX_OUT_CHUNK
#define FX_OUT_CHUNK 256
#endif

/* Bring the configured pins and buses up, then announce the fixture to the host. */
void fx_core_init(void);

/* Feed one received byte. A newline completes a request and dispatches it. */
void fx_core_feed_byte(char c);

void fx_core_feed(const char *data, size_t len);

/* Called from the main loop: forwards streamed UART traffic to the host as notifications. */
void fx_core_poll(void);

#ifdef __cplusplus
}
#endif
#endif /* FIXTURE_CORE_H */
