/* The RP2350 side of fixture_hal.h. This is the only file that knows about the Pico SDK.
 *
 * Generated by pinside. Regenerating overwrites this file.
 */

#include <stdio.h>
#include <string.h>

#include "fixture_config.h"
#include "fixture_hal.h"
#include "hardware/adc.h"
#include "hardware/gpio.h"
#include "hardware/i2c.h"
#include "hardware/spi.h"
#include "hardware/uart.h"
#include "pico/stdlib.h"

/* The RP2350 ADC is 12-bit against its own 3.3 V analogue supply. */
#define FX_ADC_FULL_SCALE 4095
#define FX_ADC_REFERENCE_MV 3300

static uart_inst_t* uart_of(uint8_t index) { return index == 0 ? uart0 : uart1; }
static i2c_inst_t* i2c_of(uint8_t index) { return index == 0 ? i2c0 : i2c1; }
static spi_inst_t* spi_of(uint8_t index) { return index == 0 ? spi0 : spi1; }

void fx_hal_write(const char* data, size_t len) {
  fwrite(data, 1, len, stdout);
  /* The core writes a response in chunks, so flushing here keeps a long one moving rather than
   * waiting for the stdio buffer to fill. */
  fflush(stdout);
}

uint64_t fx_hal_millis(void) { return to_ms_since_boot(get_absolute_time()); }

void fx_hal_gpio_configure(uint8_t pin, int direction, int pull) {
  gpio_init(pin);
  gpio_set_pulls(pin, pull == FX_PULL_UP, pull == FX_PULL_DOWN);
  if (direction == FX_DIR_INPUT) {
    gpio_set_dir(pin, GPIO_IN);
  } else if (direction == FX_DIR_OPEN_DRAIN) {
    /* Open drain is an input that becomes a driven low only while asserted, so the fixture
     * never fights a pull-up the DUT already has on the line. */
    gpio_put(pin, 0);
    gpio_set_dir(pin, GPIO_IN);
  } else {
    gpio_set_dir(pin, GPIO_OUT);
  }
}

bool fx_hal_gpio_get(uint8_t pin) { return gpio_get(pin); }

void fx_hal_gpio_set(uint8_t pin, bool level) {
  if (gpio_get_dir(pin) != GPIO_OUT) {
    gpio_put(pin, level);
    gpio_set_dir(pin, GPIO_OUT);
    return;
  }
  gpio_put(pin, level);
}

void fx_hal_gpio_release(uint8_t pin) { gpio_set_dir(pin, GPIO_IN); }

uint16_t fx_hal_adc_read(uint8_t adc_channel) {
  adc_select_input(adc_channel);
  return adc_read();
}

uint16_t fx_hal_adc_full_scale(void) { return FX_ADC_FULL_SCALE; }
uint16_t fx_hal_adc_reference_mv(void) { return FX_ADC_REFERENCE_MV; }

void fx_hal_uart_configure(uint8_t index, uint32_t baud, uint8_t data_bits, uint8_t stop_bits,
                           int parity) {
  uart_inst_t* u = uart_of(index);
  uart_init(u, baud);
  uart_parity_t p = UART_PARITY_NONE;
  if (parity == FX_PARITY_EVEN) p = UART_PARITY_EVEN;
  if (parity == FX_PARITY_ODD) p = UART_PARITY_ODD;
  uart_set_format(u, data_bits, stop_bits, p);
  uart_set_fifo_enabled(u, true);
}

size_t fx_hal_uart_write(uint8_t index, const uint8_t* data, size_t len) {
  uart_write_blocking(uart_of(index), data, len);
  return len;
}

size_t fx_hal_uart_read(uint8_t index, uint8_t* data, size_t max) {
  uart_inst_t* u = uart_of(index);
  size_t n = 0;
  while (n < max && uart_is_readable(u)) data[n++] = (uint8_t)uart_getc(u);
  return n;
}

int fx_hal_i2c_write(uint8_t index, uint8_t address, const uint8_t* data, size_t len,
                     bool hold_bus) {
  int rc = i2c_write_blocking(i2c_of(index), address, data, len, hold_bus);
  return rc < 0 ? -1 : 0;
}

int fx_hal_i2c_read(uint8_t index, uint8_t address, uint8_t* data, size_t len) {
  int rc = i2c_read_blocking(i2c_of(index), address, data, len, false);
  return rc < 0 ? -1 : 0;
}

void fx_hal_spi_configure(uint8_t index, uint32_t hz, uint8_t mode) {
  spi_inst_t* s = spi_of(index);
  spi_init(s, hz);
  spi_set_format(s, 8, (mode & 2) ? SPI_CPOL_1 : SPI_CPOL_0, (mode & 1) ? SPI_CPHA_1 : SPI_CPHA_0,
                 SPI_MSB_FIRST);
}

void fx_hal_spi_transfer(uint8_t index, const uint8_t* tx, uint8_t* rx, size_t len) {
  spi_write_read_blocking(spi_of(index), tx, rx, len);
}
