/* The fixture's channel tables: what is wired where, and what each line is called.
 *
 * Everything here is derived from PINSIDE__CONFIG_SOURCE and checked against
 * PINSIDE__DUT_BOARD before it was written. Edit the config and regenerate;
 * editing this file means the firmware and the board can disagree without anything noticing.
 *
 * Generated by pinside PINSIDE__VERSION on PINSIDE__GENERATED_AT.
 */
#ifndef FIXTURE_CONFIG_H
#define FIXTURE_CONFIG_H

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Longest channel name the protocol will accept, including the terminator. */
#define FX_NAME_MAX PINSIDE__NAME_MAX

#define FX_GPIO_COUNT PINSIDE__GPIO_COUNT
#define FX_ADC_COUNT PINSIDE__ADC_COUNT
#define FX_UART_COUNT PINSIDE__UART_COUNT
#define FX_I2C_COUNT PINSIDE__I2C_COUNT
#define FX_SPI_COUNT PINSIDE__SPI_COUNT

/* A pin role a bus does not use. */
#define FX_PIN_NONE 0xFF

enum { FX_ROLE_MASTER = 0, FX_ROLE_MONITOR = 1 };

typedef struct {
  const char* name;
  const char* probe; /* the DUT signal this lands on */
  const char* description;
  uint8_t pin;
  uint8_t direction; /* FX_DIR_* */
  uint8_t pull;      /* FX_PULL_* */
  bool active_low;
  bool initial_asserted;
} fx_gpio_desc;

typedef struct {
  const char* name;
  const char* probe;
  const char* description;
  uint8_t pin;
  uint8_t adc;            /* converter input index */
  uint16_t divider_milli; /* external divider ratio x1000; 2000 means a 2:1 divider */
  int32_t nominal_mv;     /* -1 when the config gave no expected value */
  int32_t tolerance_mv;
} fx_adc_desc;

typedef struct {
  const char* name;
  const char* description;
  const char* probe_summary; /* "tx=DUT_RXD rx=DUT_TXD ..." for fixture.channels */
  uint8_t index;             /* peripheral instance */
  uint32_t baud;
  uint8_t data_bits;
  uint8_t stop_bits;
  uint8_t parity; /* FX_PARITY_* */
  bool stream;    /* push received bytes to the host unasked */
  int8_t guard;   /* index into fx_gpio, or -1 */
  uint8_t pin_tx, pin_rx, pin_cts, pin_rts;
} fx_uart_desc;

typedef struct {
  const char* name;
  const char* description;
  const char* probe_summary;
  uint8_t index;
  uint32_t hz;
  bool pullups; /* enable the MCU's own pull-ups on SDA/SCL */
  int8_t guard;
  uint8_t pin_sda, pin_scl;
} fx_i2c_desc;

typedef struct {
  const char* name;
  const char* description;
  const char* probe_summary;
  uint8_t index;
  uint32_t hz;
  uint8_t mode; /* 0-3 */
  uint8_t role; /* FX_ROLE_* */
  int8_t guard;
  uint8_t pin_rx, pin_cs, pin_sck, pin_tx;
} fx_spi_desc;

extern const fx_gpio_desc fx_gpio[];
extern const fx_adc_desc fx_adc[];
extern const fx_uart_desc fx_uart[];
extern const fx_i2c_desc fx_i2c[];
extern const fx_spi_desc fx_spi[];

extern const size_t fx_gpio_count;
extern const size_t fx_adc_count;
extern const size_t fx_uart_count;
extern const size_t fx_i2c_count;
extern const size_t fx_spi_count;

extern const char fx_fixture_name[];
extern const char fx_fixture_version[];
extern const char fx_target_mcu[];
extern const char fx_dut_board[];
extern const char fx_config_hash[];
extern const uint32_t fx_clock_hz;

#ifdef __cplusplus
}
#endif
#endif /* FIXTURE_CONFIG_H */
