/* JSON-RPC 2.0 over the USB CDC line: one request per line, one response per line.
 *
 * The DUT-facing behaviour is all table-driven from fixture_config.c, so this file is the same
 * for every fixture pinside generates. It holds no SDK headers, which is what lets test/run.sh
 * build it on a host against a mock HAL.
 *
 * Two deliberate simplifications, both safe for the traffic this protocol carries:
 *   * The JSON reader only looks up keys at the top level of an object. It skips nested values
 *     correctly, so "params" is reachable, but there is no general document model.
 *   * Payloads travel as hex strings. Base64 would be denser; hex is trivial to verify by eye
 *     in a log, and an agent reading a capture cares more about that than about bytes on the wire.
 *
 * Generated by pinside. Regenerating overwrites this file.
 */

#include "fixture_core.h"

#include <string.h>

#include "fixture_config.h"
#include "fixture_hal.h"

/* ------------------------------------------------------------------ JSON reading */

typedef struct {
  const char* p;
  size_t n;
} fx_str;

static const char* skip_ws(const char* p, const char* end) {
  while (p < end && (*p == ' ' || *p == '\t' || *p == '\n' || *p == '\r')) p++;
  return p;
}

static const char* skip_string(const char* p, const char* end) {
  if (p >= end || *p != '"') return NULL;
  p++;
  while (p < end) {
    if (*p == '\\') {
      p += 2;
      continue;
    }
    if (*p == '"') return p + 1;
    p++;
  }
  return NULL;
}

/* Advance past one complete JSON value, whatever its depth. */
static const char* skip_value(const char* p, const char* end) {
  p = skip_ws(p, end);
  if (p >= end) return NULL;
  if (*p == '"') return skip_string(p, end);
  if (*p == '{' || *p == '[') {
    char open = *p;
    char close = (open == '{') ? '}' : ']';
    int depth = 0;
    while (p < end) {
      if (*p == '"') {
        p = skip_string(p, end);
        if (!p) return NULL;
        continue;
      }
      if (*p == open) depth++;
      if (*p == close) {
        depth--;
        if (depth == 0) return p + 1;
      }
      p++;
    }
    return NULL;
  }
  while (p < end && *p != ',' && *p != '}' && *p != ']' && *p != ' ' && *p != '\t' && *p != '\n' &&
         *p != '\r')
    p++;
  return p;
}

/* Find key at the top level of the object starting at p. */
static bool obj_get(const char* p, const char* end, const char* key, fx_str* out) {
  p = skip_ws(p, end);
  if (p >= end || *p != '{') return false;
  p++;
  size_t keylen = strlen(key);
  for (;;) {
    p = skip_ws(p, end);
    if (p >= end || *p == '}') return false;
    const char* name = p + 1;
    const char* after = skip_string(p, end);
    if (!after) return false;
    size_t namelen = (size_t)(after - name - 1);
    p = skip_ws(after, end);
    if (p >= end || *p != ':') return false;
    p = skip_ws(p + 1, end);
    const char* value = p;
    const char* value_end = skip_value(p, end);
    if (!value_end) return false;
    if (namelen == keylen && memcmp(name, key, keylen) == 0) {
      out->p = value;
      out->n = (size_t)(value_end - value);
      return true;
    }
    p = skip_ws(value_end, end);
    if (p < end && *p == ',') {
      p++;
      continue;
    }
    return false;
  }
}

static bool str_value(fx_str v, char* buf, size_t cap) {
  if (v.n < 2 || v.p[0] != '"') return false;
  const char* p = v.p + 1;
  const char* end = v.p + v.n - 1;
  size_t o = 0;
  while (p < end && o + 1 < cap) {
    char c = *p++;
    if (c == '\\' && p < end) {
      char e = *p++;
      switch (e) {
        case 'n': c = '\n'; break;
        case 't': c = '\t'; break;
        case 'r': c = '\r'; break;
        case 'b': c = '\b'; break;
        case 'f': c = '\f'; break;
        case 'u': /* no UTF-16 in a channel name; keep the placeholder visible */
          if (end - p >= 4) p += 4;
          c = '?';
          break;
        default: c = e; break;
      }
    }
    buf[o++] = c;
  }
  buf[o] = '\0';
  return p >= end;
}

static bool int_value(fx_str v, long* out) {
  const char* p = v.p;
  const char* end = v.p + v.n;
  bool neg = false;
  if (p < end && (*p == '-' || *p == '+')) neg = (*p++ == '-');
  if (p >= end) return false;
  long acc = 0;
  bool any = false;
  while (p < end && *p >= '0' && *p <= '9') {
    acc = acc * 10 + (*p++ - '0');
    any = true;
  }
  if (!any) return false;
  *out = neg ? -acc : acc;
  return true;
}

static bool bool_value(fx_str v, bool* out) {
  if (v.n == 4 && memcmp(v.p, "true", 4) == 0) {
    *out = true;
    return true;
  }
  if (v.n == 5 && memcmp(v.p, "false", 5) == 0) {
    *out = false;
    return true;
  }
  return false;
}

/* ------------------------------------------------------------------ JSON writing */

/* A response is streamed, not assembled. fixture.channels on a real fixture runs to several
 * kilobytes -- more than a fixture wants to hold -- and buffering it whole was the first thing
 * the host tests caught. Chunking has one consequence worth knowing: once the first chunk has
 * gone out a response cannot be retracted, so every failure must be decided before writing. */
typedef struct {
  char buf[FX_OUT_CHUNK];
  size_t len;
} fx_out;

static void out_drain(fx_out* o) {
  if (o->len == 0) return;
  fx_hal_write(o->buf, o->len);
  o->len = 0;
}

static void out_raw(fx_out* o, const char* s, size_t n) {
  while (n > 0) {
    size_t room = sizeof(o->buf) - o->len;
    if (room == 0) {
      out_drain(o);
      room = sizeof(o->buf);
    }
    size_t take = n < room ? n : room;
    memcpy(o->buf + o->len, s, take);
    o->len += take;
    s += take;
    n -= take;
  }
}

static void out_lit(fx_out* o, const char* s) { out_raw(o, s, strlen(s)); }

static void out_char(fx_out* o, char c) { out_raw(o, &c, 1); }

static void out_escaped(fx_out* o, const char* s) {
  out_char(o, '"');
  for (; *s; s++) {
    switch (*s) {
      case '"': out_lit(o, "\\\""); break;
      case '\\': out_lit(o, "\\\\"); break;
      case '\n': out_lit(o, "\\n"); break;
      case '\r': out_lit(o, "\\r"); break;
      case '\t': out_lit(o, "\\t"); break;
      default:
        if ((unsigned char)*s < 0x20) {
          static const char hex[] = "0123456789abcdef";
          char esc[6] = {'\\', 'u', '0', '0', 0, 0};
          esc[4] = hex[((unsigned char)*s >> 4) & 0xf];
          esc[5] = hex[(unsigned char)*s & 0xf];
          out_raw(o, esc, 6);
        } else {
          out_char(o, *s);
        }
    }
  }
  out_char(o, '"');
}

static void out_long(fx_out* o, long v) {
  char tmp[24];
  size_t i = sizeof(tmp);
  unsigned long mag = (v < 0) ? (unsigned long)(-(v + 1)) + 1UL : (unsigned long)v;
  do {
    tmp[--i] = (char)('0' + (mag % 10));
    mag /= 10;
  } while (mag && i);
  if (v < 0 && i) tmp[--i] = '-';
  out_raw(o, tmp + i, sizeof(tmp) - i);
}

static void out_key(fx_out* o, const char* key) {
  out_escaped(o, key);
  out_char(o, ':');
}

static void out_kv_str(fx_out* o, const char* key, const char* value) {
  out_key(o, key);
  out_escaped(o, value);
}

static void out_kv_long(fx_out* o, const char* key, long value) {
  out_key(o, key);
  out_long(o, value);
}

static void out_kv_bool(fx_out* o, const char* key, bool value) {
  out_key(o, key);
  out_lit(o, value ? "true" : "false");
}

static void out_flush(fx_out* o) {
  out_char(o, '\n');
  out_drain(o);
}

/* ------------------------------------------------------------------ hex payloads */

static int hex_digit(char c) {
  if (c >= '0' && c <= '9') return c - '0';
  if (c >= 'a' && c <= 'f') return c - 'a' + 10;
  if (c >= 'A' && c <= 'F') return c - 'A' + 10;
  return -1;
}

static long hex_decode(const char* s, uint8_t* out, size_t cap) {
  size_t n = 0;
  while (*s) {
    int hi = hex_digit(*s++);
    if (hi < 0 || !*s) return -1;
    int lo = hex_digit(*s++);
    if (lo < 0) return -1;
    if (n >= cap) return -1;
    out[n++] = (uint8_t)((hi << 4) | lo);
  }
  return (long)n;
}

static void out_hex(fx_out* o, const uint8_t* data, size_t len) {
  static const char hex[] = "0123456789abcdef";
  out_char(o, '"');
  for (size_t i = 0; i < len; i++) {
    out_char(o, hex[data[i] >> 4]);
    out_char(o, hex[data[i] & 0xf]);
  }
  out_char(o, '"');
}

/* ------------------------------------------------------------------ channel lookup */

static int find_gpio(const char* name) {
  for (size_t i = 0; i < fx_gpio_count; i++)
    if (strcmp(fx_gpio[i].name, name) == 0) return (int)i;
  return -1;
}

static int find_adc(const char* name) {
  for (size_t i = 0; i < fx_adc_count; i++)
    if (strcmp(fx_adc[i].name, name) == 0) return (int)i;
  return -1;
}

static int find_uart(const char* name) {
  for (size_t i = 0; i < fx_uart_count; i++)
    if (strcmp(fx_uart[i].name, name) == 0) return (int)i;
  return -1;
}

static int find_i2c(const char* name) {
  for (size_t i = 0; i < fx_i2c_count; i++)
    if (strcmp(fx_i2c[i].name, name) == 0) return (int)i;
  return -1;
}

static int find_spi(const char* name) {
  for (size_t i = 0; i < fx_spi_count; i++)
    if (strcmp(fx_spi[i].name, name) == 0) return (int)i;
  return -1;
}

/* ------------------------------------------------------------------ gpio semantics */

static bool gpio_is_asserted(const fx_gpio_desc* g) {
  bool level = fx_hal_gpio_get(g->pin);
  return g->active_low ? !level : level;
}

static void gpio_drive(const fx_gpio_desc* g, bool assert_it) {
  if (g->direction == FX_DIR_OPEN_DRAIN) {
    /* Only ever pull towards the asserted rail; releasing means going high-Z, which is what
     * keeps the fixture from fighting the DUT's own pull-up on a line like ESP_EN. */
    if (assert_it)
      fx_hal_gpio_set(g->pin, g->active_low ? false : true);
    else
      fx_hal_gpio_release(g->pin);
    return;
  }
  fx_hal_gpio_set(g->pin, g->active_low ? !assert_it : assert_it);
}

/* A bus whose lines the DUT also drives may only be mastered while its guard is asserted. */
static bool guard_satisfied(int8_t guard) {
  if (guard < 0) return true;
  return gpio_is_asserted(&fx_gpio[guard]);
}

static const char* guard_name(int8_t guard) { return guard < 0 ? "" : fx_gpio[guard].name; }

/* ------------------------------------------------------------------ responses */

typedef struct {
  fx_str id;
  bool has_id;
} fx_req;

static void out_head(fx_out* o, const fx_req* req) {
  o->len = 0;
  out_lit(o, "{\"jsonrpc\":\"2.0\",\"id\":");
  if (req->has_id)
    out_raw(o, req->id.p, req->id.n);
  else
    out_lit(o, "null");
}

static void reply_error(const fx_req* req, long code, const char* message, const char* data) {
  fx_out o;
  out_head(&o, req);
  out_lit(&o, ",\"error\":{");
  out_kv_long(&o, "code", code);
  out_char(&o, ',');
  out_kv_str(&o, "message", message);
  if (data && *data) {
    out_char(&o, ',');
    out_kv_str(&o, "data", data);
  }
  out_lit(&o, "}}");
  out_flush(&o);
}

static void reply_ok_empty(const fx_req* req) {
  fx_out o;
  out_head(&o, req);
  out_lit(&o, ",\"result\":{}}");
  out_flush(&o);
}

static void notify_begin(fx_out* o, const char* method) {
  o->len = 0;
  out_lit(o, "{\"jsonrpc\":\"2.0\",\"method\":");
  out_escaped(o, method);
  out_lit(o, ",\"params\":{");
}

static void notify_end(fx_out* o) {
  out_lit(o, "}}");
  out_flush(o);
}

/* ------------------------------------------------------------------ methods */

static void emit_gpio_state(fx_out* o, const fx_gpio_desc* g) {
  out_lit(o, "{");
  out_kv_str(o, "channel", g->name);
  out_char(o, ',');
  out_kv_str(o, "probe", g->probe);
  out_char(o, ',');
  out_kv_long(o, "pin", g->pin);
  out_char(o, ',');
  out_kv_bool(o, "level", fx_hal_gpio_get(g->pin));
  out_char(o, ',');
  out_kv_bool(o, "asserted", gpio_is_asserted(g));
  out_lit(o, "}");
}

static void emit_adc_state(fx_out* o, const fx_adc_desc* a) {
  uint16_t raw = fx_hal_adc_read(a->adc);
  uint32_t full = fx_hal_adc_full_scale();
  uint32_t at_pin_mv = full ? (uint32_t)raw * fx_hal_adc_reference_mv() / full : 0;
  /* divider_milli is the ratio the external network divides by, times 1000. */
  long mv = (long)((uint64_t)at_pin_mv * a->divider_milli / 1000u);

  out_lit(o, "{");
  out_kv_str(o, "channel", a->name);
  out_char(o, ',');
  out_kv_str(o, "probe", a->probe);
  out_char(o, ',');
  out_kv_long(o, "millivolts", mv);
  out_char(o, ',');
  out_kv_long(o, "raw", raw);
  if (a->nominal_mv >= 0) {
    long low = a->nominal_mv - a->tolerance_mv;
    long high = a->nominal_mv + a->tolerance_mv;
    out_char(o, ',');
    out_kv_long(o, "nominal_mv", a->nominal_mv);
    out_char(o, ',');
    out_kv_bool(o, "in_range", mv >= low && mv <= high);
  }
  out_lit(o, "}");
}

static void method_info(const fx_req* req) {
  fx_out o;
  out_head(&o, req);
  out_lit(&o, ",\"result\":{");
  out_kv_str(&o, "fixture", fx_fixture_name);
  out_char(&o, ',');
  out_kv_str(&o, "version", fx_fixture_version);
  out_char(&o, ',');
  out_kv_str(&o, "mcu", fx_target_mcu);
  out_char(&o, ',');
  out_kv_str(&o, "dut_board", fx_dut_board);
  out_char(&o, ',');
  out_kv_str(&o, "config_hash", fx_config_hash);
  out_char(&o, ',');
  out_kv_long(&o, "uptime_ms", (long)fx_hal_millis());
  out_char(&o, ',');
  out_key(&o, "counts");
  out_lit(&o, "{");
  out_kv_long(&o, "gpio", (long)fx_gpio_count);
  out_char(&o, ',');
  out_kv_long(&o, "adc", (long)fx_adc_count);
  out_char(&o, ',');
  out_kv_long(&o, "uart", (long)fx_uart_count);
  out_char(&o, ',');
  out_kv_long(&o, "i2c", (long)fx_i2c_count);
  out_char(&o, ',');
  out_kv_long(&o, "spi", (long)fx_spi_count);
  out_lit(&o, "}}}");
  out_flush(&o);
}

static void emit_bus_entry(fx_out* o, const char* kind, const char* name, const char* probe_list,
                           int8_t guard, bool stream) {
  out_lit(o, "{");
  out_kv_str(o, "channel", name);
  out_char(o, ',');
  out_kv_str(o, "kind", kind);
  out_char(o, ',');
  out_kv_str(o, "probes", probe_list);
  out_char(o, ',');
  out_kv_str(o, "guard", guard_name(guard));
  out_char(o, ',');
  out_kv_bool(o, "stream", stream);
  out_lit(o, "}");
}

static void method_channels(const fx_req* req) {
  fx_out o;
  out_head(&o, req);
  out_lit(&o, ",\"result\":[");
  bool first = true;
  for (size_t i = 0; i < fx_gpio_count; i++) {
    if (!first) out_char(&o, ',');
    first = false;
    out_lit(&o, "{");
    out_kv_str(&o, "channel", fx_gpio[i].name);
    out_char(&o, ',');
    out_kv_str(&o, "kind", "gpio");
    out_char(&o, ',');
    out_kv_str(&o, "probe", fx_gpio[i].probe);
    out_char(&o, ',');
    out_kv_long(&o, "pin", fx_gpio[i].pin);
    out_char(&o, ',');
    out_kv_bool(&o, "writable", fx_gpio[i].direction != FX_DIR_INPUT);
    out_char(&o, ',');
    out_kv_str(&o, "description", fx_gpio[i].description);
    out_lit(&o, "}");
  }
  for (size_t i = 0; i < fx_adc_count; i++) {
    if (!first) out_char(&o, ',');
    first = false;
    out_lit(&o, "{");
    out_kv_str(&o, "channel", fx_adc[i].name);
    out_char(&o, ',');
    out_kv_str(&o, "kind", "adc");
    out_char(&o, ',');
    out_kv_str(&o, "probe", fx_adc[i].probe);
    out_char(&o, ',');
    out_kv_long(&o, "pin", fx_adc[i].pin);
    out_char(&o, ',');
    out_kv_str(&o, "description", fx_adc[i].description);
    out_lit(&o, "}");
  }
  for (size_t i = 0; i < fx_uart_count; i++) {
    if (!first) out_char(&o, ',');
    first = false;
    emit_bus_entry(&o, "uart", fx_uart[i].name, fx_uart[i].probe_summary, fx_uart[i].guard,
                   fx_uart[i].stream);
  }
  for (size_t i = 0; i < fx_i2c_count; i++) {
    if (!first) out_char(&o, ',');
    first = false;
    emit_bus_entry(&o, "i2c", fx_i2c[i].name, fx_i2c[i].probe_summary, fx_i2c[i].guard, false);
  }
  for (size_t i = 0; i < fx_spi_count; i++) {
    if (!first) out_char(&o, ',');
    first = false;
    emit_bus_entry(&o, "spi", fx_spi[i].name, fx_spi[i].probe_summary, fx_spi[i].guard, false);
  }
  out_lit(&o, "]}");
  out_flush(&o);
}

/* Pull a required string parameter. Replies with an error and returns false if absent. */
static bool want_str(const fx_req* req, fx_str params, bool have_params, const char* key, char* buf,
                     size_t cap) {
  fx_str v;
  if (!have_params || !obj_get(params.p, params.p + params.n, key, &v) || !str_value(v, buf, cap)) {
    reply_error(req, -32602, "invalid params", key);
    return false;
  }
  return true;
}

static bool want_long(const fx_req* req, fx_str params, bool have_params, const char* key,
                      long* out) {
  fx_str v;
  if (!have_params || !obj_get(params.p, params.p + params.n, key, &v) || !int_value(v, out)) {
    reply_error(req, -32602, "invalid params", key);
    return false;
  }
  return true;
}

static void method_gpio_read(const fx_req* req, fx_str params, bool have_params) {
  char name[FX_NAME_MAX];
  if (!want_str(req, params, have_params, "channel", name, sizeof(name))) return;
  int idx = find_gpio(name);
  if (idx < 0) {
    reply_error(req, -32001, "no such gpio channel", name);
    return;
  }
  fx_out o;
  out_head(&o, req);
  out_lit(&o, ",\"result\":");
  emit_gpio_state(&o, &fx_gpio[idx]);
  out_lit(&o, "}");
  out_flush(&o);
}

static void method_gpio_write(const fx_req* req, fx_str params, bool have_params) {
  char name[FX_NAME_MAX];
  if (!want_str(req, params, have_params, "channel", name, sizeof(name))) return;
  int idx = find_gpio(name);
  if (idx < 0) {
    reply_error(req, -32001, "no such gpio channel", name);
    return;
  }
  const fx_gpio_desc* g = &fx_gpio[idx];
  if (g->direction == FX_DIR_INPUT) {
    reply_error(req, -32002, "channel is an input", name);
    return;
  }
  fx_str v;
  bool assert_it = false;
  if (!have_params || !obj_get(params.p, params.p + params.n, "assert", &v) ||
      !bool_value(v, &assert_it)) {
    reply_error(req, -32602, "invalid params", "assert");
    return;
  }
  gpio_drive(g, assert_it);
  fx_out o;
  out_head(&o, req);
  out_lit(&o, ",\"result\":");
  emit_gpio_state(&o, g);
  out_lit(&o, "}");
  out_flush(&o);
}

static void method_gpio_snapshot(const fx_req* req) {
  fx_out o;
  out_head(&o, req);
  out_lit(&o, ",\"result\":[");
  for (size_t i = 0; i < fx_gpio_count; i++) {
    if (i) out_char(&o, ',');
    emit_gpio_state(&o, &fx_gpio[i]);
  }
  out_lit(&o, "]}");
  out_flush(&o);
}

static void method_adc_read(const fx_req* req, fx_str params, bool have_params) {
  char name[FX_NAME_MAX];
  if (!want_str(req, params, have_params, "channel", name, sizeof(name))) return;
  int idx = find_adc(name);
  if (idx < 0) {
    reply_error(req, -32001, "no such adc channel", name);
    return;
  }
  fx_out o;
  out_head(&o, req);
  out_lit(&o, ",\"result\":");
  emit_adc_state(&o, &fx_adc[idx]);
  out_lit(&o, "}");
  out_flush(&o);
}

static void method_adc_snapshot(const fx_req* req) {
  fx_out o;
  out_head(&o, req);
  out_lit(&o, ",\"result\":[");
  for (size_t i = 0; i < fx_adc_count; i++) {
    if (i) out_char(&o, ',');
    emit_adc_state(&o, &fx_adc[i]);
  }
  out_lit(&o, "]}");
  out_flush(&o);
}

static void method_uart_write(const fx_req* req, fx_str params, bool have_params) {
  char name[FX_NAME_MAX];
  char hex[FX_PAYLOAD_MAX * 2 + 1];
  if (!want_str(req, params, have_params, "channel", name, sizeof(name))) return;
  int idx = find_uart(name);
  if (idx < 0) {
    reply_error(req, -32001, "no such uart channel", name);
    return;
  }
  if (!want_str(req, params, have_params, "hex", hex, sizeof(hex))) return;
  uint8_t payload[FX_PAYLOAD_MAX];
  long n = hex_decode(hex, payload, sizeof(payload));
  if (n < 0) {
    reply_error(req, -32602, "invalid params", "hex must be an even number of hex digits");
    return;
  }
  if (!guard_satisfied(fx_uart[idx].guard)) {
    reply_error(req, -32003, "guard not asserted", guard_name(fx_uart[idx].guard));
    return;
  }
  size_t written = fx_hal_uart_write(fx_uart[idx].index, payload, (size_t)n);
  fx_out o;
  out_head(&o, req);
  out_lit(&o, ",\"result\":{");
  out_kv_long(&o, "written", (long)written);
  out_lit(&o, "}}");
  out_flush(&o);
}

static void method_uart_read(const fx_req* req, fx_str params, bool have_params) {
  char name[FX_NAME_MAX];
  if (!want_str(req, params, have_params, "channel", name, sizeof(name))) return;
  int idx = find_uart(name);
  if (idx < 0) {
    reply_error(req, -32001, "no such uart channel", name);
    return;
  }
  long max = FX_PAYLOAD_MAX;
  fx_str v;
  if (have_params && obj_get(params.p, params.p + params.n, "max", &v)) {
    if (!int_value(v, &max) || max < 0) {
      reply_error(req, -32602, "invalid params", "max");
      return;
    }
  }
  if (max > FX_PAYLOAD_MAX) max = FX_PAYLOAD_MAX;
  uint8_t payload[FX_PAYLOAD_MAX];
  size_t n = fx_hal_uart_read(fx_uart[idx].index, payload, (size_t)max);
  fx_out o;
  out_head(&o, req);
  out_lit(&o, ",\"result\":{");
  out_key(&o, "hex");
  out_hex(&o, payload, n);
  out_char(&o, ',');
  out_kv_long(&o, "length", (long)n);
  out_lit(&o, "}}");
  out_flush(&o);
}

static void method_uart_configure(const fx_req* req, fx_str params, bool have_params) {
  char name[FX_NAME_MAX];
  long baud = 0;
  if (!want_str(req, params, have_params, "channel", name, sizeof(name))) return;
  int idx = find_uart(name);
  if (idx < 0) {
    reply_error(req, -32001, "no such uart channel", name);
    return;
  }
  if (!want_long(req, params, have_params, "baud", &baud)) return;
  if (baud <= 0) {
    reply_error(req, -32602, "invalid params", "baud must be positive");
    return;
  }
  const fx_uart_desc* u = &fx_uart[idx];
  fx_hal_uart_configure(u->index, (uint32_t)baud, u->data_bits, u->stop_bits, u->parity);
  reply_ok_empty(req);
}

static void method_i2c_scan(const fx_req* req, fx_str params, bool have_params) {
  char name[FX_NAME_MAX];
  if (!want_str(req, params, have_params, "channel", name, sizeof(name))) return;
  int idx = find_i2c(name);
  if (idx < 0) {
    reply_error(req, -32001, "no such i2c channel", name);
    return;
  }
  if (!guard_satisfied(fx_i2c[idx].guard)) {
    reply_error(req, -32003, "guard not asserted", guard_name(fx_i2c[idx].guard));
    return;
  }
  fx_out o;
  out_head(&o, req);
  out_lit(&o, ",\"result\":{\"addresses\":[");
  bool first = true;
  uint8_t probe = 0;
  /* 0x00-0x07 and 0x78-0x7f are reserved by the I2C specification. */
  for (uint8_t addr = 0x08; addr < 0x78; addr++) {
    if (fx_hal_i2c_read(fx_i2c[idx].index, addr, &probe, 1) < 0) continue;
    if (!first) out_char(&o, ',');
    first = false;
    out_long(&o, addr);
  }
  out_lit(&o, "]}}");
  out_flush(&o);
}

static bool i2c_address_param(const fx_req* req, fx_str params, bool have_params, long* addr) {
  if (!want_long(req, params, have_params, "address", addr)) return false;
  if (*addr < 0 || *addr > 0x7f) {
    reply_error(req, -32602, "invalid params", "address must be a 7-bit value");
    return false;
  }
  return true;
}

static void method_i2c_write(const fx_req* req, fx_str params, bool have_params) {
  char name[FX_NAME_MAX];
  char hex[FX_PAYLOAD_MAX * 2 + 1];
  long addr = 0;
  if (!want_str(req, params, have_params, "channel", name, sizeof(name))) return;
  int idx = find_i2c(name);
  if (idx < 0) {
    reply_error(req, -32001, "no such i2c channel", name);
    return;
  }
  if (!i2c_address_param(req, params, have_params, &addr)) return;
  if (!want_str(req, params, have_params, "hex", hex, sizeof(hex))) return;
  uint8_t payload[FX_PAYLOAD_MAX];
  long n = hex_decode(hex, payload, sizeof(payload));
  if (n < 0) {
    reply_error(req, -32602, "invalid params", "hex must be an even number of hex digits");
    return;
  }
  if (!guard_satisfied(fx_i2c[idx].guard)) {
    reply_error(req, -32003, "guard not asserted", guard_name(fx_i2c[idx].guard));
    return;
  }
  int rc = fx_hal_i2c_write(fx_i2c[idx].index, (uint8_t)addr, payload, (size_t)n, false);
  if (rc < 0) {
    reply_error(req, -32004, "i2c write failed", name);
    return;
  }
  reply_ok_empty(req);
}

static void method_i2c_read(const fx_req* req, fx_str params, bool have_params) {
  char name[FX_NAME_MAX];
  long addr = 0;
  long length = 0;
  if (!want_str(req, params, have_params, "channel", name, sizeof(name))) return;
  int idx = find_i2c(name);
  if (idx < 0) {
    reply_error(req, -32001, "no such i2c channel", name);
    return;
  }
  if (!i2c_address_param(req, params, have_params, &addr)) return;
  if (!want_long(req, params, have_params, "length", &length)) return;
  if (length <= 0 || length > FX_PAYLOAD_MAX) {
    reply_error(req, -32602, "invalid params", "length out of range");
    return;
  }
  if (!guard_satisfied(fx_i2c[idx].guard)) {
    reply_error(req, -32003, "guard not asserted", guard_name(fx_i2c[idx].guard));
    return;
  }
  uint8_t payload[FX_PAYLOAD_MAX];
  if (fx_hal_i2c_read(fx_i2c[idx].index, (uint8_t)addr, payload, (size_t)length) < 0) {
    reply_error(req, -32004, "i2c read failed", name);
    return;
  }
  fx_out o;
  out_head(&o, req);
  out_lit(&o, ",\"result\":{");
  out_key(&o, "hex");
  out_hex(&o, payload, (size_t)length);
  out_lit(&o, "}}");
  out_flush(&o);
}

static void method_spi_transfer(const fx_req* req, fx_str params, bool have_params) {
  char name[FX_NAME_MAX];
  char hex[FX_PAYLOAD_MAX * 2 + 1];
  if (!want_str(req, params, have_params, "channel", name, sizeof(name))) return;
  int idx = find_spi(name);
  if (idx < 0) {
    reply_error(req, -32001, "no such spi channel", name);
    return;
  }
  if (fx_spi[idx].role != FX_ROLE_MASTER) {
    reply_error(req, -32005, "channel is monitor-only", name);
    return;
  }
  if (!want_str(req, params, have_params, "hex", hex, sizeof(hex))) return;
  uint8_t tx[FX_PAYLOAD_MAX];
  uint8_t rx[FX_PAYLOAD_MAX];
  long n = hex_decode(hex, tx, sizeof(tx));
  if (n < 0) {
    reply_error(req, -32602, "invalid params", "hex must be an even number of hex digits");
    return;
  }
  if (!guard_satisfied(fx_spi[idx].guard)) {
    reply_error(req, -32003, "guard not asserted", guard_name(fx_spi[idx].guard));
    return;
  }
  fx_hal_spi_transfer(fx_spi[idx].index, tx, rx, (size_t)n);
  fx_out o;
  out_head(&o, req);
  out_lit(&o, ",\"result\":{");
  out_key(&o, "hex");
  out_hex(&o, rx, (size_t)n);
  out_lit(&o, "}}");
  out_flush(&o);
}

/* ------------------------------------------------------------------ dispatch */

static void dispatch(const char* line, size_t len) {
  fx_req req = {{NULL, 0}, false};
  const char* end = line + len;

  fx_str id;
  if (obj_get(line, end, "id", &id)) {
    req.id = id;
    req.has_id = true;
  }

  fx_str method_v;
  char method[FX_NAME_MAX * 2];
  if (!obj_get(line, end, "method", &method_v) || !str_value(method_v, method, sizeof(method))) {
    reply_error(&req, -32600, "invalid request", "no method");
    return;
  }

  fx_str params = {NULL, 0};
  bool have_params = obj_get(line, end, "params", &params);

  if (strcmp(method, "fixture.info") == 0) return method_info(&req);
  if (strcmp(method, "fixture.channels") == 0) return method_channels(&req);
  if (strcmp(method, "gpio.read") == 0) return method_gpio_read(&req, params, have_params);
  if (strcmp(method, "gpio.write") == 0) return method_gpio_write(&req, params, have_params);
  if (strcmp(method, "gpio.snapshot") == 0) return method_gpio_snapshot(&req);
  if (strcmp(method, "adc.read") == 0) return method_adc_read(&req, params, have_params);
  if (strcmp(method, "adc.snapshot") == 0) return method_adc_snapshot(&req);
  if (strcmp(method, "uart.write") == 0) return method_uart_write(&req, params, have_params);
  if (strcmp(method, "uart.read") == 0) return method_uart_read(&req, params, have_params);
  if (strcmp(method, "uart.configure") == 0)
    return method_uart_configure(&req, params, have_params);
  if (strcmp(method, "i2c.scan") == 0) return method_i2c_scan(&req, params, have_params);
  if (strcmp(method, "i2c.write") == 0) return method_i2c_write(&req, params, have_params);
  if (strcmp(method, "i2c.read") == 0) return method_i2c_read(&req, params, have_params);
  if (strcmp(method, "spi.transfer") == 0) return method_spi_transfer(&req, params, have_params);

  reply_error(&req, -32601, "method not found", method);
}

/* ------------------------------------------------------------------ line assembly */

static char g_line[FX_LINE_MAX];
static size_t g_line_len;
static bool g_line_too_long;

void fx_core_feed_byte(char c) {
  if (c == '\r') return;
  if (c != '\n') {
    if (g_line_len < sizeof(g_line))
      g_line[g_line_len++] = c;
    else
      g_line_too_long = true;
    return;
  }

  if (g_line_too_long) {
    fx_req none = {{NULL, 0}, false};
    reply_error(&none, -32600, "invalid request", "line longer than FX_LINE_MAX");
  } else if (g_line_len > 0) {
    dispatch(g_line, g_line_len);
  }
  g_line_len = 0;
  g_line_too_long = false;
}

void fx_core_feed(const char* data, size_t len) {
  for (size_t i = 0; i < len; i++) fx_core_feed_byte(data[i]);
}

/* ------------------------------------------------------------------ startup and streaming */

void fx_core_init(void) {
  g_line_len = 0;
  g_line_too_long = false;

  for (size_t i = 0; i < fx_gpio_count; i++) {
    const fx_gpio_desc* g = &fx_gpio[i];
    fx_hal_gpio_configure(g->pin, g->direction, g->pull);
    if (g->direction != FX_DIR_INPUT) gpio_drive(g, g->initial_asserted);
  }
  for (size_t i = 0; i < fx_uart_count; i++) {
    const fx_uart_desc* u = &fx_uart[i];
    fx_hal_uart_configure(u->index, u->baud, u->data_bits, u->stop_bits, u->parity);
  }
  for (size_t i = 0; i < fx_spi_count; i++) {
    const fx_spi_desc* s = &fx_spi[i];
    if (s->role == FX_ROLE_MASTER) fx_hal_spi_configure(s->index, s->hz, s->mode);
  }

  fx_out o;
  notify_begin(&o, "fixture.ready");
  out_kv_str(&o, "fixture", fx_fixture_name);
  out_char(&o, ',');
  out_kv_str(&o, "version", fx_fixture_version);
  out_char(&o, ',');
  out_kv_str(&o, "config_hash", fx_config_hash);
  notify_end(&o);
}

void fx_core_poll(void) {
  /* Anything arriving on a streamed UART is pushed to the agent unasked, so a log line shows up
   * as soon as the DUT emits it rather than whenever someone remembers to poll. */
  for (size_t i = 0; i < fx_uart_count; i++) {
    const fx_uart_desc* u = &fx_uart[i];
    if (!u->stream) continue;
    uint8_t payload[FX_PAYLOAD_MAX];
    size_t n = fx_hal_uart_read(u->index, payload, sizeof(payload));
    if (n == 0) continue;
    fx_out o;
    notify_begin(&o, "uart.data");
    out_kv_str(&o, "channel", u->name);
    out_char(&o, ',');
    out_key(&o, "hex");
    out_hex(&o, payload, n);
    out_char(&o, ',');
    out_kv_long(&o, "length", (long)n);
    out_char(&o, ',');
    out_kv_long(&o, "t_ms", (long)fx_hal_millis());
    notify_end(&o);
  }
}
