/* Fixture entry point: wait for the host, then shuttle bytes between it and the protocol core.
 *
 * The host link is the SDK's stdio USB CDC. Going straight to TinyUSB would mean carrying a
 * tusb_config.h and a descriptor table in every generated project, for one bulk serial endpoint
 * the SDK already provides.
 *
 * Generated by pinside. Regenerating overwrites this file.
 */

#include <stdio.h>

#include "fixture_config.h"
#include "fixture_core.h"
#include "pico/stdlib.h"

int main(void) {
  set_sys_clock_khz(fx_clock_hz / 1000, true);
  stdio_init_all();

  /* Say nothing until the port is open, or the ready notification is lost into a device nobody
   * is listening to and the agent starts against a fixture that never announced itself. */
  while (!stdio_usb_connected()) sleep_ms(10);

  fx_core_init();

  for (;;) {
    int c = getchar_timeout_us(0);
    while (c != PICO_ERROR_TIMEOUT) {
      fx_core_feed_byte((char)c);
      c = getchar_timeout_us(0);
    }
    fx_core_poll();
  }
}
