/* Generated by pinside. Regenerating overwrites this file. */

#include "mock_hal.h"

#include <string.h>

#include "fixture_hal.h"

mock_state mock;

void mock_reset(void) {
  memset(&mock, 0, sizeof(mock));
  for (int i = 0; i < MOCK_PINS; i++) mock.direction[i] = FX_DIR_INPUT;
}

void fx_hal_write(const char *data, size_t len) {
  if (mock.out_len + len >= MOCK_OUT_MAX) return;
  memcpy(mock.out + mock.out_len, data, len);
  mock.out_len += len;
  mock.out[mock.out_len] = '\0';
}

const char *mock_last_line(void) {
  static char line[MOCK_OUT_MAX];
  if (mock.out_len == 0) return "";
  size_t end = mock.out_len;
  while (end > 0 && (mock.out[end - 1] == '\n' || mock.out[end - 1] == '\r')) end--;
  size_t start = end;
  while (start > 0 && mock.out[start - 1] != '\n') start--;
  size_t n = end - start;
  memcpy(line, mock.out + start, n);
  line[n] = '\0';
  return line;
}

bool mock_out_contains(const char *needle) { return strstr(mock.out, needle) != NULL; }

uint64_t fx_hal_millis(void) { return mock.millis; }

void fx_hal_gpio_configure(uint8_t pin, int direction, int pull) {
  mock.direction[pin] = direction;
  mock.pull[pin] = pull;
  mock.floating[pin] = (direction != FX_DIR_OUTPUT);
}

bool fx_hal_gpio_get(uint8_t pin) { return mock.level[pin]; }

void fx_hal_gpio_set(uint8_t pin, bool level) {
  mock.level[pin] = level;
  mock.floating[pin] = false;
}

void fx_hal_gpio_release(uint8_t pin) {
  mock.floating[pin] = true;
  /* A released open-drain line is pulled back up by whatever is on the board. */
  if (mock.pull[pin] != FX_PULL_DOWN) mock.level[pin] = true;
}

uint16_t fx_hal_adc_read(uint8_t adc_channel) {
  return adc_channel < 8 ? mock.adc[adc_channel] : 0;
}

uint16_t fx_hal_adc_full_scale(void) { return 4095; }
uint16_t fx_hal_adc_reference_mv(void) { return 3300; }

void fx_hal_uart_configure(uint8_t index, uint32_t baud, uint8_t data_bits, uint8_t stop_bits,
                           int parity) {
  (void)data_bits;
  (void)stop_bits;
  (void)parity;
  if (index < 2) mock.uart_baud[index] = baud;
}

size_t fx_hal_uart_write(uint8_t index, const uint8_t *data, size_t len) {
  if (index >= 2) return 0;
  size_t room = MOCK_FIFO - mock.uart_tx_len[index];
  if (len > room) len = room;
  memcpy(mock.uart_tx[index] + mock.uart_tx_len[index], data, len);
  mock.uart_tx_len[index] += len;
  return len;
}

size_t fx_hal_uart_read(uint8_t index, uint8_t *data, size_t max) {
  if (index >= 2) return 0;
  size_t n = mock.uart_rx_len[index];
  if (n > max) n = max;
  memcpy(data, mock.uart_rx[index], n);
  memmove(mock.uart_rx[index], mock.uart_rx[index] + n, mock.uart_rx_len[index] - n);
  mock.uart_rx_len[index] -= n;
  return n;
}

int fx_hal_i2c_write(uint8_t index, uint8_t address, const uint8_t *data, size_t len,
                     bool hold_bus) {
  (void)hold_bus;
  if (index >= 2 || !mock.i2c_present[index][address]) return -1;
  if (len > MOCK_FIFO) len = MOCK_FIFO;
  memcpy(mock.i2c_last_write, data, len);
  mock.i2c_last_write_len = len;
  return 0;
}

int fx_hal_i2c_read(uint8_t index, uint8_t address, uint8_t *data, size_t len) {
  if (index >= 2 || !mock.i2c_present[index][address]) return -1;
  memset(data, mock.i2c_reply, len);
  return 0;
}

void fx_hal_spi_configure(uint8_t index, uint32_t hz, uint8_t mode) {
  (void)index;
  (void)hz;
  (void)mode;
}

void fx_hal_spi_transfer(uint8_t index, const uint8_t *tx, uint8_t *rx, size_t len) {
  (void)index;
  size_t n = len > MOCK_FIFO ? MOCK_FIFO : len;
  memcpy(mock.spi_last_tx, tx, n);
  mock.spi_last_tx_len = n;
  memset(rx, mock.spi_reply, len);
}
