/* Test double for fixture_hal.h: a fixture with no hardware under it.
 *
 * Generated by pinside. Regenerating overwrites this file.
 */
#ifndef MOCK_HAL_H
#define MOCK_HAL_H

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>

#define MOCK_PINS 64
#define MOCK_OUT_MAX 65536
#define MOCK_FIFO 512

typedef struct {
  char out[MOCK_OUT_MAX];
  size_t out_len;

  bool level[MOCK_PINS];
  int direction[MOCK_PINS];
  int pull[MOCK_PINS];
  bool floating[MOCK_PINS];   /* released: high-Z, reading whatever the DUT presents */

  uint16_t adc[8];
  uint64_t millis;

  /* What the DUT is pretending to say back on each UART. */
  uint8_t uart_rx[2][MOCK_FIFO];
  size_t uart_rx_len[2];
  uint8_t uart_tx[2][MOCK_FIFO];
  size_t uart_tx_len[2];
  uint32_t uart_baud[2];

  /* Which I2C addresses answer, and what a read returns. */
  bool i2c_present[2][128];
  uint8_t i2c_reply;
  uint8_t i2c_last_write[MOCK_FIFO];
  size_t i2c_last_write_len;

  uint8_t spi_reply;          /* every SPI read byte comes back as this */
  uint8_t spi_last_tx[MOCK_FIFO];
  size_t spi_last_tx_len;
} mock_state;

extern mock_state mock;

void mock_reset(void);
/* The single line most recently written to the host, terminator stripped. */
const char *mock_last_line(void);
/* Does the captured output contain this substring? */
bool mock_out_contains(const char *needle);

#endif /* MOCK_HAL_H */
